In [3]:
import torch 

In [4]:
x = torch.arange(0,2*3*4).view(2,3,4)
x

tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]],

        [[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]]])

In [5]:
x.view(3,2,4)

tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7]],

        [[ 8,  9, 10, 11],
         [12, 13, 14, 15]],

        [[16, 17, 18, 19],
         [20, 21, 22, 23]]])

In [6]:
x.permute(1,2,0).shape, x.permute(1,2,0)


(torch.Size([3, 4, 2]),
 tensor([[[ 0, 12],
          [ 1, 13],
          [ 2, 14],
          [ 3, 15]],
 
         [[ 4, 16],
          [ 5, 17],
          [ 6, 18],
          [ 7, 19]],
 
         [[ 8, 20],
          [ 9, 21],
          [10, 22],
          [11, 23]]]))

In [7]:
x.permute(0,2,1).shape,x.permute(0,2,1)

(torch.Size([2, 4, 3]),
 tensor([[[ 0,  4,  8],
          [ 1,  5,  9],
          [ 2,  6, 10],
          [ 3,  7, 11]],
 
         [[12, 16, 20],
          [13, 17, 21],
          [14, 18, 22],
          [15, 19, 23]]]))

In [8]:
x.permute(1,0,2).shape, x.permute(1,0,2)

(torch.Size([3, 2, 4]),
 tensor([[[ 0,  1,  2,  3],
          [12, 13, 14, 15]],
 
         [[ 4,  5,  6,  7],
          [16, 17, 18, 19]],
 
         [[ 8,  9, 10, 11],
          [20, 21, 22, 23]]]))

In [9]:
x.permute(2,1,0).shape, x.permute(2,1,0)

(torch.Size([4, 3, 2]),
 tensor([[[ 0, 12],
          [ 4, 16],
          [ 8, 20]],
 
         [[ 1, 13],
          [ 5, 17],
          [ 9, 21]],
 
         [[ 2, 14],
          [ 6, 18],
          [10, 22]],
 
         [[ 3, 15],
          [ 7, 19],
          [11, 23]]]))

In [10]:
x.permute(2,0,1).shape, x.permute(2,0,1)

(torch.Size([4, 2, 3]),
 tensor([[[ 0,  4,  8],
          [12, 16, 20]],
 
         [[ 1,  5,  9],
          [13, 17, 21]],
 
         [[ 2,  6, 10],
          [14, 18, 22]],
 
         [[ 3,  7, 11],
          [15, 19, 23]]]))