In [1]:
import torch
import torch.nn as nn

In [2]:
B, T, C = 4, 3, 2
x = torch.arange(0, B * T * C).view(B,T,C).float()
x

tensor([[[ 0.,  1.],
         [ 2.,  3.],
         [ 4.,  5.]],

        [[ 6.,  7.],
         [ 8.,  9.],
         [10., 11.]],

        [[12., 13.],
         [14., 15.],
         [16., 17.]],

        [[18., 19.],
         [20., 21.],
         [22., 23.]]])

In [3]:
layer_norm = nn.LayerNorm(normalized_shape=C,elementwise_affine=False,bias=False)
layer_norm(x)

tensor([[[-1.0000,  1.0000],
         [-1.0000,  1.0000],
         [-1.0000,  1.0000]],

        [[-1.0000,  1.0000],
         [-1.0000,  1.0000],
         [-1.0000,  1.0000]],

        [[-1.0000,  1.0000],
         [-1.0000,  1.0000],
         [-1.0000,  1.0000]],

        [[-1.0000,  1.0000],
         [-1.0000,  1.0000],
         [-1.0000,  1.0000]]])

In [4]:
x.view(B,T*C).mean(dim=-1),torch.var(x.view(B,T*C),dim=-1)

(tensor([ 2.5000,  8.5000, 14.5000, 20.5000]),
 tensor([3.5000, 3.5000, 3.5000, 3.5000]))

In [5]:
layer_norm.eps, layer_norm.parameters()

(1e-05, <generator object Module.parameters at 0x000001B3AA2D5660>)

In [6]:
for parameter in layer_norm.parameters():
    print(parameter)

In [7]:
x = torch.tensor([[
         [76.,  2., 43.],
         [79., 50., 29.],
         [59., 78., 73.],
         [95., 94., 76.],
         [ 9., 74., 64.]],

        [[76., 87., 50.],
         [ 2., 65., 44.],
         [74.,  9., 82.],
         [83., 54., 82.],
         [ 6., 97., 52.]],

        [[88., 19., 95.],
         [14., 96., 96.],
         [93., 58.,  0.],
         [19., 37.,  6.],
         [28., 23.,  7.]],

        [[ 7., 54., 59.],
         [57., 30., 18.],
         [88., 89., 63.],
         [56., 75., 56.],
         [63., 23., 73.]]])

B,T,C = x.shape
normalized_shape = (T,C)
x.view(B,T*C).mean(dim=-1),x.view(B,T*C).var(dim=-1,correction=False)

(tensor([60.0667, 57.5333, 45.2667, 54.0667]),
 tensor([ 751.6622,  887.8489, 1344.1956,  561.9289]))

In [8]:
# Normalize
for i in range(0,4):               # loop through each matrix
  mean = x[i].mean()               # mean         
  var = x[i].var(unbiased=False)   # variance
  layer_norm = (x[i]-mean)/(torch.sqrt(var+0.00005))

  print(f"μ = {mean:.4f}")            
  print(f"σ^{2} = {var:.4f}") 
  print(layer_norm)
  print("="*50)

μ = 60.0667
σ^2 = 751.6622
tensor([[ 0.5812, -2.1179, -0.6225],
        [ 0.6906, -0.3672, -1.1331],
        [-0.0389,  0.6541,  0.4717],
        [ 1.2742,  1.2377,  0.5812],
        [-1.8626,  0.5082,  0.1435]])
μ = 57.5333
σ^2 = 887.8489
tensor([[ 0.6198,  0.9889, -0.2528],
        [-1.8637,  0.2506, -0.4542],
        [ 0.5526, -1.6288,  0.8211],
        [ 0.8547, -0.1186,  0.8211],
        [-1.7295,  1.3245, -0.1857]])
μ = 45.2667
σ^2 = 1344.1956
tensor([[ 1.1656, -0.7164,  1.3565],
        [-0.8528,  1.3838,  1.3838],
        [ 1.3019,  0.3473, -1.2347],
        [-0.7164, -0.2255, -1.0710],
        [-0.4710, -0.6073, -1.0437]])
μ = 54.0667
σ^2 = 561.9289
tensor([[-1.9855, -0.0028,  0.2081],
        [ 0.1237, -1.0153, -1.5215],
        [ 1.4315,  1.4737,  0.3769],
        [ 0.0816,  0.8831,  0.0816],
        [ 0.3769, -1.3106,  0.7987]])


In [9]:
layer_norm = nn.LayerNorm(normalized_shape=normalized_shape,elementwise_affine=True)
layer_norm(x)

tensor([[[ 0.5812, -2.1179, -0.6225],
         [ 0.6906, -0.3672, -1.1331],
         [-0.0389,  0.6541,  0.4717],
         [ 1.2742,  1.2377,  0.5812],
         [-1.8626,  0.5082,  0.1435]],

        [[ 0.6198,  0.9889, -0.2528],
         [-1.8637,  0.2506, -0.4542],
         [ 0.5526, -1.6288,  0.8211],
         [ 0.8547, -0.1186,  0.8211],
         [-1.7295,  1.3245, -0.1857]],

        [[ 1.1656, -0.7164,  1.3565],
         [-0.8528,  1.3838,  1.3838],
         [ 1.3019,  0.3473, -1.2347],
         [-0.7164, -0.2255, -1.0710],
         [-0.4710, -0.6073, -1.0437]],

        [[-1.9855, -0.0028,  0.2081],
         [ 0.1237, -1.0153, -1.5215],
         [ 1.4315,  1.4737,  0.3769],
         [ 0.0816,  0.8831,  0.0816],
         [ 0.3769, -1.3106,  0.7987]]], grad_fn=<NativeLayerNormBackward0>)

In [11]:
batch, sentence_length, embedding_dim = 6, 5, 3
torch.manual_seed(0)
x = torch.randn(batch, sentence_length, embedding_dim)
layer_norm = nn.LayerNorm(embedding_dim)
layer_norm(x)

tensor([[[-0.6752, -0.7385,  1.4137],
         [-1.4053,  0.8398,  0.5655],
         [ 0.3750, -1.3684,  0.9934],
         [-1.4138,  0.7348,  0.6790],
         [-1.4073,  0.8243,  0.5830]],

        [[ 1.3774, -0.4110, -0.9664],
         [-0.8612,  1.4013, -0.5401],
         [-1.0923, -0.2318,  1.3241],
         [ 1.3485, -1.0432, -0.3053],
         [-1.4023,  0.5423,  0.8599]],

        [[ 1.4043, -0.8468, -0.5575],
         [ 0.3294, -1.3557,  1.0263],
         [ 0.1931, -1.3097,  1.1166],
         [ 0.1740, -1.3024,  1.1284],
         [-1.1555, -0.1283,  1.2838]],

        [[ 1.4137, -0.6742, -0.7395],
         [-1.4077,  0.5861,  0.8215],
         [ 1.3596, -0.3431, -1.0165],
         [ 1.4127, -0.6502, -0.7625],
         [-1.0251, -0.3312,  1.3563]],

        [[-0.8029, -0.6068,  1.4097],
         [-0.6944, -0.7198,  1.4141],
         [ 0.6351,  0.7767, -1.4118],
         [ 1.3668, -0.9979, -0.3689],
         [-1.1218, -0.1848,  1.3066]],

        [[-0.9878,  1.3704, -0.3826],
  

In [23]:
x.mean(dim=-1)

tensor([[-0.8429,  0.3689, -0.7030, -0.2017,  0.8248],
        [-1.0986,  0.6530, -0.0145, -0.0029,  1.0531],
        [-0.1703, -0.0709,  0.3976,  0.3771,  0.0952],
        [-0.2511,  0.4184, -0.1481, -0.0994,  1.8918],
        [-0.3152, -0.0669,  0.3075,  0.8099, -0.3368],
        [ 1.0425,  0.3961,  0.4103, -0.5229,  0.2552]])

In [25]:
x.var(dim=-1,correction=False)

tensor([[0.1756, 0.3264, 1.0651, 0.5638, 0.2509],
        [0.3820, 0.0100, 1.9893, 0.3119, 0.3846],
        [0.6322, 0.0968, 0.0474, 0.1355, 0.1109],
        [3.2621, 0.6012, 0.0575, 0.2069, 1.2538],
        [2.2937, 0.4870, 1.5997, 1.6531, 1.3275],
        [0.4303, 0.8099, 1.6396, 0.3399, 0.0222]])

In [32]:
for parameter in layer_norm.parameters():
    print(parameter)

Parameter containing:
tensor([1., 1., 1.], requires_grad=True)
Parameter containing:
tensor([0., 0., 0.], requires_grad=True)
