In [60]:
import torch
import torch.nn as nn

In [61]:
B, T, C = 4, 3, 2
x = torch.arange(0, B * T * C).view(B,T,C).float()
x

tensor([[[ 0.,  1.],
         [ 2.,  3.],
         [ 4.,  5.]],

        [[ 6.,  7.],
         [ 8.,  9.],
         [10., 11.]],

        [[12., 13.],
         [14., 15.],
         [16., 17.]],

        [[18., 19.],
         [20., 21.],
         [22., 23.]]])

In [62]:
layer_norm = nn.LayerNorm(normalized_shape=C,elementwise_affine=False,bias=False)
layer_norm(x)

tensor([[[-1.0000,  1.0000],
         [-1.0000,  1.0000],
         [-1.0000,  1.0000]],

        [[-1.0000,  1.0000],
         [-1.0000,  1.0000],
         [-1.0000,  1.0000]],

        [[-1.0000,  1.0000],
         [-1.0000,  1.0000],
         [-1.0000,  1.0000]],

        [[-1.0000,  1.0000],
         [-1.0000,  1.0000],
         [-1.0000,  1.0000]]])

In [63]:
x.view(B,T*C).mean(dim=-1),torch.var(x.view(B,T*C),dim=-1)

(tensor([ 2.5000,  8.5000, 14.5000, 20.5000]),
 tensor([3.5000, 3.5000, 3.5000, 3.5000]))

In [64]:
layer_norm.eps, layer_norm.parameters()

(1e-05, <generator object Module.parameters at 0x0000014EA803C970>)

In [65]:
for parameter in layer_norm.parameters():
    print(parameter)

In [66]:
x = torch.tensor([[
         [76.,  2., 43.],
         [79., 50., 29.],
         [59., 78., 73.],
         [95., 94., 76.],
         [ 9., 74., 64.]],

        [[76., 87., 50.],
         [ 2., 65., 44.],
         [74.,  9., 82.],
         [83., 54., 82.],
         [ 6., 97., 52.]],

        [[88., 19., 95.],
         [14., 96., 96.],
         [93., 58.,  0.],
         [19., 37.,  6.],
         [28., 23.,  7.]],

        [[ 7., 54., 59.],
         [57., 30., 18.],
         [88., 89., 63.],
         [56., 75., 56.],
         [63., 23., 73.]]])

B,T,C = x.shape
normalized_shape = (T,C)
x.view(B,T*C).mean(dim=-1),x.view(B,T*C).var(dim=-1,correction=False)

(tensor([60.0667, 57.5333, 45.2667, 54.0667]),
 tensor([ 751.6622,  887.8489, 1344.1956,  561.9289]))

In [67]:
# Normalize
for i in range(0,4):               # loop through each matrix
  mean = x[i].mean()               # mean         
  var = x[i].var(unbiased=False)   # variance
  layer_norm = (x[i]-mean)/(torch.sqrt(var+0.00005))

  print(f"μ = {mean:.4f}")            
  print(f"σ^{2} = {var:.4f}") 
  print(layer_norm)
  print("="*50)

μ = 60.0667
σ^2 = 751.6622
tensor([[ 0.5812, -2.1179, -0.6225],
        [ 0.6906, -0.3672, -1.1331],
        [-0.0389,  0.6541,  0.4717],
        [ 1.2742,  1.2377,  0.5812],
        [-1.8626,  0.5082,  0.1435]])
μ = 57.5333
σ^2 = 887.8489
tensor([[ 0.6198,  0.9889, -0.2528],
        [-1.8637,  0.2506, -0.4542],
        [ 0.5526, -1.6288,  0.8211],
        [ 0.8547, -0.1186,  0.8211],
        [-1.7295,  1.3245, -0.1857]])
μ = 45.2667
σ^2 = 1344.1956
tensor([[ 1.1656, -0.7164,  1.3565],
        [-0.8528,  1.3838,  1.3838],
        [ 1.3019,  0.3473, -1.2347],
        [-0.7164, -0.2255, -1.0710],
        [-0.4710, -0.6073, -1.0437]])
μ = 54.0667
σ^2 = 561.9289
tensor([[-1.9855, -0.0028,  0.2081],
        [ 0.1237, -1.0153, -1.5215],
        [ 1.4315,  1.4737,  0.3769],
        [ 0.0816,  0.8831,  0.0816],
        [ 0.3769, -1.3106,  0.7987]])


In [68]:
layer_norm = nn.LayerNorm(normalized_shape=normalized_shape,elementwise_affine=True)
layer_norm(x)

tensor([[[ 0.5812, -2.1179, -0.6225],
         [ 0.6906, -0.3672, -1.1331],
         [-0.0389,  0.6541,  0.4717],
         [ 1.2742,  1.2377,  0.5812],
         [-1.8626,  0.5082,  0.1435]],

        [[ 0.6198,  0.9889, -0.2528],
         [-1.8637,  0.2506, -0.4542],
         [ 0.5526, -1.6288,  0.8211],
         [ 0.8547, -0.1186,  0.8211],
         [-1.7295,  1.3245, -0.1857]],

        [[ 1.1656, -0.7164,  1.3565],
         [-0.8528,  1.3838,  1.3838],
         [ 1.3019,  0.3473, -1.2347],
         [-0.7164, -0.2255, -1.0710],
         [-0.4710, -0.6073, -1.0437]],

        [[-1.9855, -0.0028,  0.2081],
         [ 0.1237, -1.0153, -1.5215],
         [ 1.4315,  1.4737,  0.3769],
         [ 0.0816,  0.8831,  0.0816],
         [ 0.3769, -1.3106,  0.7987]]], grad_fn=<NativeLayerNormBackward0>)