In [7]:
import torch
import torch.nn as nn
import torch.nn.functional as F

In [8]:
B, C, H, W = 2, 3, 4 , 4

x = torch.arange(0,B*C*H*W).view(B,C,H,W).float()
x

tensor([[[[ 0.,  1.,  2.,  3.],
          [ 4.,  5.,  6.,  7.],
          [ 8.,  9., 10., 11.],
          [12., 13., 14., 15.]],

         [[16., 17., 18., 19.],
          [20., 21., 22., 23.],
          [24., 25., 26., 27.],
          [28., 29., 30., 31.]],

         [[32., 33., 34., 35.],
          [36., 37., 38., 39.],
          [40., 41., 42., 43.],
          [44., 45., 46., 47.]]],


        [[[48., 49., 50., 51.],
          [52., 53., 54., 55.],
          [56., 57., 58., 59.],
          [60., 61., 62., 63.]],

         [[64., 65., 66., 67.],
          [68., 69., 70., 71.],
          [72., 73., 74., 75.],
          [76., 77., 78., 79.]],

         [[80., 81., 82., 83.],
          [84., 85., 86., 87.],
          [88., 89., 90., 91.],
          [92., 93., 94., 95.]]]])

In [9]:
batchnorm = nn.BatchNorm(3,affine=False)
batchnorm(x), batchnorm.eps

AttributeError: module 'torch.nn' has no attribute 'BatchNorm'

In [ ]:
x.mean(dim=0)

tensor([[[24., 25., 26., 27.],
         [28., 29., 30., 31.],
         [32., 33., 34., 35.],
         [36., 37., 38., 39.]],

        [[40., 41., 42., 43.],
         [44., 45., 46., 47.],
         [48., 49., 50., 51.],
         [52., 53., 54., 55.]],

        [[56., 57., 58., 59.],
         [60., 61., 62., 63.],
         [64., 65., 66., 67.],
         [68., 69., 70., 71.]]])

In [ ]:
x.sum(dim=1)

tensor([[[ 48.,  51.,  54.,  57.],
         [ 60.,  63.,  66.,  69.],
         [ 72.,  75.,  78.,  81.],
         [ 84.,  87.,  90.,  93.]],

        [[192., 195., 198., 201.],
         [204., 207., 210., 213.],
         [216., 219., 222., 225.],
         [228., 231., 234., 237.]]])

In [ ]:
x

tensor([[[[ 0.,  1.,  2.,  3.],
          [ 4.,  5.,  6.,  7.],
          [ 8.,  9., 10., 11.],
          [12., 13., 14., 15.]],

         [[16., 17., 18., 19.],
          [20., 21., 22., 23.],
          [24., 25., 26., 27.],
          [28., 29., 30., 31.]],

         [[32., 33., 34., 35.],
          [36., 37., 38., 39.],
          [40., 41., 42., 43.],
          [44., 45., 46., 47.]]],


        [[[48., 49., 50., 51.],
          [52., 53., 54., 55.],
          [56., 57., 58., 59.],
          [60., 61., 62., 63.]],

         [[64., 65., 66., 67.],
          [68., 69., 70., 71.],
          [72., 73., 74., 75.],
          [76., 77., 78., 79.]],

         [[80., 81., 82., 83.],
          [84., 85., 86., 87.],
          [88., 89., 90., 91.],
          [92., 93., 94., 95.]]]])

In [ ]:
torch.manual_seed(2)
input_data = torch.randn(3, 1, 8, 8) 
input_data2 = input_data.view(input_data.size(0), 1, -1)
mean = torch.mean(input_data2, dim=2, keepdim=True)
variance = torch.var(input_data2, dim=2, unbiased=True, keepdim=True)
mean, variance

(tensor([[[-0.1020]],
 
         [[ 0.1346]],
 
         [[ 0.1132]]]),
 tensor([[[0.9619]],
 
         [[0.8456]],
 
         [[0.9186]]]))

In [ ]:
input_data.mean(dim=0),input_data.var(dim=0)

(tensor([[[ 0.0121,  0.2009, -0.7279, -0.9142, -0.4205,  0.8289, -0.1937,
            0.2062],
          [ 0.3503, -0.1583, -0.1482, -0.0080,  0.2868, -0.0885, -0.4668,
            0.0171],
          [ 0.1256, -0.7726, -0.3529,  1.0303,  0.9312, -0.4955,  0.9101,
            0.2041],
          [ 1.0414,  0.2085,  0.1362,  1.5805,  0.3914,  0.2898, -0.3473,
           -0.2551],
          [-0.2216,  0.9994,  0.0764,  0.0767,  0.0398, -0.8332,  0.1956,
           -0.2748],
          [ 0.4264,  0.3593, -0.1674, -0.4784, -0.6627, -0.1040, -0.2648,
            0.3769],
          [-0.0404,  0.1464, -0.6358,  0.6435,  0.3905,  0.9785, -0.5542,
            1.1058],
          [ 0.0750, -0.3775,  0.4957, -0.8697, -1.0398,  0.5577, -0.4006,
           -0.3124]]]),
 tensor([[[1.1949e+00, 6.1307e-01, 1.3110e+00, 3.9242e-01, 1.1992e+00,
           1.0007e+00, 7.8404e-01, 4.1058e-01],
          [2.4732e+00, 5.0977e-01, 1.4691e-01, 9.5048e-02, 4.2961e-01,
           3.3949e-01, 6.4634e-01, 3.7665e+00],

In [ ]:
input_data

tensor([[[[-1.0408,  0.9166, -1.3042, -1.1097, -1.2188,  1.1676, -1.0574,
           -0.1188],
          [-0.9078,  0.3452, -0.5713, -0.2351,  1.0076, -0.7529, -0.2250,
           -0.4327],
          [-1.5071, -0.4586, -0.8480,  0.5266,  0.0299, -0.0498,  1.0651,
            0.8860],
          [ 0.4640, -0.4986,  0.1289,  2.7631,  0.1405,  1.1191,  0.3152,
            1.7528],
          [-0.7650,  1.8299, -0.2784, -0.2719, -1.2944, -0.0243, -0.2354,
           -0.7087],
          [ 1.1566,  0.4296, -1.1874, -0.7468, -0.9320, -0.8579, -0.9647,
           -0.0991],
          [-1.0190,  0.3157, -1.6036,  1.8493,  0.0447,  1.5853, -0.5912,
            1.1312],
          [ 0.7562, -1.2023, -0.5833, -0.4407, -1.9791,  0.7787, -0.7749,
           -0.1398]]],


        [[[ 1.1414, -0.6354, -1.4702, -0.2134, -0.8707,  1.6159, -0.2356,
            0.9444],
          [ 2.1134, -0.9754,  0.1757, -0.1319, -0.2735,  0.3355,  0.1885,
            2.1432],
          [ 0.8527,  0.0965, -0.0625,  0.8269,

In [ ]:
norm_layer = nn.BatchNorm2d(1)
norm_layer(input_data)

tensor([[[[-1.1445,  0.9120, -1.4213, -1.2169, -1.3315,  1.1757, -1.1620,
           -0.1759],
          [-1.0048,  0.3117, -0.6513, -0.2980,  1.0076, -0.8420, -0.2874,
           -0.5056],
          [-1.6345, -0.5328, -0.9420,  0.5022, -0.0196, -0.1034,  1.0680,
            0.8799],
          [ 0.4365, -0.5749,  0.0844,  2.8520,  0.0966,  1.1247,  0.2802,
            1.7905],
          [-0.8547,  1.8715, -0.3435, -0.3367, -1.4110, -0.0766, -0.2983,
           -0.7956],
          [ 1.1642,  0.4003, -1.2985, -0.8356, -1.0302, -0.9523, -1.0646,
           -0.1552],
          [-1.1216,  0.2806, -1.7358,  1.8920, -0.0040,  1.6145, -0.6722,
            1.1375],
          [ 0.7435, -1.3142, -0.6639, -0.5140, -2.1304,  0.7671, -0.8651,
           -0.1979]]],


        [[[ 1.1482, -0.7186, -1.5957, -0.2752, -0.9658,  1.6467, -0.2986,
            0.9412],
          [ 2.1694, -1.0758,  0.1336, -0.1896, -0.3384,  0.3015,  0.1471,
            2.2007],
          [ 0.8449,  0.0503, -0.1167,  0.8177,