In [51]:
import torch

In [52]:
B, T, C = 4, 3, 2
x = torch.arange(0, B * T * C).view(B,T,C).float()
x

tensor([[[ 0.,  1.],
         [ 2.,  3.],
         [ 4.,  5.]],

        [[ 6.,  7.],
         [ 8.,  9.],
         [10., 11.]],

        [[12., 13.],
         [14., 15.],
         [16., 17.]],

        [[18., 19.],
         [20., 21.],
         [22., 23.]]])

In [53]:
x.sum(dim=0,keepdims=True)

tensor([[[36., 40.],
         [44., 48.],
         [52., 56.]]])

In [54]:
x.sum(dim=1,keepdims=True)

tensor([[[ 6.,  9.]],

        [[24., 27.]],

        [[42., 45.]],

        [[60., 63.]]])

In [55]:
x.sum(dim=2,keepdims=True)

tensor([[[ 1.],
         [ 5.],
         [ 9.]],

        [[13.],
         [17.],
         [21.]],

        [[25.],
         [29.],
         [33.]],

        [[37.],
         [41.],
         [45.]]])

In [56]:
I, B, T, C = 3, 2, 3, 4
x = torch.arange(0, I * B * T * C).view(I,B,T,C).float()
x

tensor([[[[ 0.,  1.,  2.,  3.],
          [ 4.,  5.,  6.,  7.],
          [ 8.,  9., 10., 11.]],

         [[12., 13., 14., 15.],
          [16., 17., 18., 19.],
          [20., 21., 22., 23.]]],


        [[[24., 25., 26., 27.],
          [28., 29., 30., 31.],
          [32., 33., 34., 35.]],

         [[36., 37., 38., 39.],
          [40., 41., 42., 43.],
          [44., 45., 46., 47.]]],


        [[[48., 49., 50., 51.],
          [52., 53., 54., 55.],
          [56., 57., 58., 59.]],

         [[60., 61., 62., 63.],
          [64., 65., 66., 67.],
          [68., 69., 70., 71.]]]])

In [57]:
x.sum(dim=0,keepdims=True)

tensor([[[[ 72.,  75.,  78.,  81.],
          [ 84.,  87.,  90.,  93.],
          [ 96.,  99., 102., 105.]],

         [[108., 111., 114., 117.],
          [120., 123., 126., 129.],
          [132., 135., 138., 141.]]]])

In [58]:
x.sum(dim=1,keepdims=True)

tensor([[[[ 12.,  14.,  16.,  18.],
          [ 20.,  22.,  24.,  26.],
          [ 28.,  30.,  32.,  34.]]],


        [[[ 60.,  62.,  64.,  66.],
          [ 68.,  70.,  72.,  74.],
          [ 76.,  78.,  80.,  82.]]],


        [[[108., 110., 112., 114.],
          [116., 118., 120., 122.],
          [124., 126., 128., 130.]]]])

In [59]:
x.sum(dim=2,keepdims=True)

tensor([[[[ 12.,  15.,  18.,  21.]],

         [[ 48.,  51.,  54.,  57.]]],


        [[[ 84.,  87.,  90.,  93.]],

         [[120., 123., 126., 129.]]],


        [[[156., 159., 162., 165.]],

         [[192., 195., 198., 201.]]]])

In [60]:
x.sum(dim=3,keepdims=True)

tensor([[[[  6.],
          [ 22.],
          [ 38.]],

         [[ 54.],
          [ 70.],
          [ 86.]]],


        [[[102.],
          [118.],
          [134.]],

         [[150.],
          [166.],
          [182.]]],


        [[[198.],
          [214.],
          [230.]],

         [[246.],
          [262.],
          [278.]]]])

In [61]:
B, C, T, R = 3, 2, 2, 2
x = torch.arange(0, B* C* T* R).view(B, C, T, R ).float()
x

tensor([[[[ 0.,  1.],
          [ 2.,  3.]],

         [[ 4.,  5.],
          [ 6.,  7.]]],


        [[[ 8.,  9.],
          [10., 11.]],

         [[12., 13.],
          [14., 15.]]],


        [[[16., 17.],
          [18., 19.]],

         [[20., 21.],
          [22., 23.]]]])

In [62]:
B, C, T, R =  2, 3, 2, 2
x = torch.arange(0, B* C* T* R).view(B, C, T, R ).float()
x

tensor([[[[ 0.,  1.],
          [ 2.,  3.]],

         [[ 4.,  5.],
          [ 6.,  7.]],

         [[ 8.,  9.],
          [10., 11.]]],


        [[[12., 13.],
          [14., 15.]],

         [[16., 17.],
          [18., 19.]],

         [[20., 21.],
          [22., 23.]]]])

In [63]:
x.sum(dim=(0))



tensor([[[12., 14.],
         [16., 18.]],

        [[20., 22.],
         [24., 26.]],

        [[28., 30.],
         [32., 34.]]])

In [64]:
x.sum((0,2,3))

tensor([ 60.,  92., 124.])

In [65]:
x.sum(0)

tensor([[[12., 14.],
         [16., 18.]],

        [[20., 22.],
         [24., 26.]],

        [[28., 30.],
         [32., 34.]]])

In [66]:
x.sum(0).sum(1).sum(-1)

tensor([ 60.,  92., 124.])

In [71]:
x.sum((0,2,-1))

tensor([ 60.,  92., 124.])